services:
  auth-service:
    build: ./auth-service
    ports:
      - "3000:3000"
    env_file:
      - ./auth-service/.env
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - app-network

  mongodb:
    image: mongo:8.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: