services:
  gateway:
    build: ./gateway
    container_name: gateway
    env_file:
      - ./gateway/.env
    ports:
      - "3010:3010"
    volumes:
      - ./gateway:/app
      - /app/node_module
    depends_on:
      - rabbitmq
    networks:
      - app-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    env_file:
      - ./auth-service/.env
    ports:
      - "3000:3000"
    volumes:
      - ./auth-service:/app
      - /app/node_module
    depends_on:
      - auth-db
      - rabbitmq
    networks:
      - app-network
        
  auth-db:
    image: mongo:8.0
    container_name: auth-db
    ports:
      - "27017:27017"
    volumes:
      - auth-db-data:/data/db
    networks:
      - app-network

  clock-service:
    build: ./clock-service
    container_name: clock-service
    env_file:
      - ./clock-service/.env
    ports:
      - "3001:3001"
    volumes:
      - ./clock-service:/app
      - /app/node_module
    depends_on:
      - clock-db
      - rabbitmq
    networks:
      - app-network
        
  clock-db:
    image: mongo:8.0
    ports:
      - "27018:27017"
    container_name: clock-db
    volumes:
      - clock-db-data:/data/db
    networks:
      - app-network

  register-service:
    build: ./register-service
    container_name: register-service
    env_file:
      - ./register-service/.env
    ports:
      - "3004:3004"
    volumes:
      - ./register-service:/app
      - /app/node_module
    depends_on:
      - register-db
      - rabbitmq
    networks:
      - app-network

  register-db:
    image: mongo:8.0
    ports:
      - "27021:27017"
    container_name: register-db
    volumes:
      - register-db-data:/data/db
    networks:
      - app-network

  image-server:
    build: ./image-server
    container_name: image-server
    env_file:
      - ./image-server/.env
    ports:
      - "3011:3011"
    volumes:
      - ./image-server:/app
      - /app/node_module
    depends_on:
      - rabbitmq
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  auth-db-data:
  clock-db-data:
  register-db-data: