services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    networks:
      - backend

  clock-service:
    build:
      context: ./clock-service
      dockerfile: Dockerfile
    networks:
      - backend

networks:
  backend:
    driver: bridge