services:
  gateway:
    build: ./gateway
    container_name: gateway
    env_file:
      - ./gateway/.env
    ports:
      - "3000:3000"
    volumes:
      - ./gateway:/app
      - /app/node_module
    depends_on:
      - rabbitmq
    networks:
      - app-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    env_file:
      - ./auth-service/.env
    ports:
      - "3008"
    volumes:
      - ./auth-service:/app
      - /app/node_module
    depends_on:
      - auth-db
      - rabbitmq
    networks:
      - app-network
        
  auth-db:
    image: mongo:8.0
    container_name: auth-db
    ports:
      - "27017:27017"
    volumes:
      - auth-db-data:/data/db
    networks:
      - app-network

  clock-service:
    build: ./clock-service
    container_name: clock-service
    env_file:
      - ./clock-service/.env
    ports:
      - "3001"
    volumes:
      - ./clock-service:/app
      - /app/node_module
    depends_on:
      - clock-db
      - rabbitmq
    networks:
      - app-network
        
  clock-db:
    image: mongo:8.0
    ports:
      - "27018:27017"
    container_name: clock-db
    volumes:
      - clock-db-data:/data/db
    networks:
      - app-network

  mail-service:
    build: ./mail-service
    container_name: mail-service
    env_file:
      - ./mail-service/.env
    ports:
      - "3002"
    volumes:
      - ./mail-service:/app
      - /app/node_module
    depends_on:
      - rabbitmq
    networks:
      - app-network

  register-service:
    build: ./register-service
    container_name: register-service
    env_file:
      - ./register-service/.env
    ports:
      - "3004"
    volumes:
      - ./register-service:/app
      - /app/node_module
    depends_on:
      - register-db
      - rabbitmq
    networks:
      - app-network

  register-db:
    image: mongo:8.0
    ports:
      - "27021:27017"
    container_name: register-db
    volumes:
      - register-db-data:/data/db
    networks:
      - app-network

  score-service:
    build: ./score-service
    container_name: score-service
    env_file:
      - ./score-service/.env
    ports:
      - "3005"
    volumes:
      - ./score-service:/app
      - /app/node_module
    depends_on:
      - score-db
      - rabbitmq
    networks:
      - app-network

  score-db:
    image: mongo:8.0
    ports:
      - "27022:27017"
    container_name: score-db
    volumes:
      - score-db-data:/data/db
    networks:
      - app-network

  target-service:
    build: ./target-service
    container_name: target-service
    env_file:
      - ./target-service/.env
    ports:
      - "3006"
    volumes:
      - ./target-service:/app
      - /app/node_module
    depends_on:
      - target-db
      - rabbitmq
    networks:
      - app-network

  target-db:
    image: mongo:8.0
    ports:
      - "27023:27017"
    container_name: target-db
    volumes:
      - target-db-data:/data/db
    networks:
      - app-network

  rabbitmq:
    build: ./rabbitmq
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  auth-db-data:
  clock-db-data:
  register-db-data:
  score-db-data:
  target-db-data: