name: 'Jest Code Coverage'
on:
    push:
        branches:
            - devops
    pull_request:
        branches:
            - devops
            
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.JS
              uses: actions/setup-node@v2
              with:
                node-version: '22'

            - name: Install dependencies
              run: npm install
              working-directory: './clock-service'

            - name: Run Tests
              run: npm test
              working-directory: './clock-service'

            - name: Jest Code Coverage
              uses: ArtiomTr/jest-coverage-report-action@v2