name: 'Jest Code Coverage'
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
            
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.JS
              uses: actions/setup-node@v2
              with:
                node-version: '20'

            - name: Install dependencies
              run: npm install
              working-directory: './api'

            - name: Run Tests
              run: npm test
              working-directory: './api'

            - name: Run ESLint
              run: npm run lint
              working-directory: api

            - name: Jest Code Coverage
              uses: ArtiomTr/jest-coverage-report-action@v2